"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var PluginType;
(function (PluginType) {
    PluginType["None"] = "none";
    PluginType["ApplicationSearchPlugin"] = "application-search-plugin";
    PluginType["UeliCommandSearchPlugin"] = "ueli-command-search-plugin";
    PluginType["ShortcutsSearchPlugin"] = "shortcuts-search-plugin";
    PluginType["EverythingSearchPlugin"] = "everything-search-plugin";
    PluginType["MdFindExecutionPlugin"] = "md-find-execution-plugin";
    PluginType["TranslationPlugin"] = "translation-plugin";
    PluginType["WebSearchPlugin"] = "websearch-plugin";
    PluginType["FileBrowserPlugin"] = "filebrowser-plugin";
    PluginType["OperatingSystemCommandsPlugin"] = "operating-system-commands-plugin";
    PluginType["OperatingSystemSettingsPlugin"] = "operating-system-settings-plugin";
    PluginType["Calculator"] = "calculator-plugin";
    PluginType["Url"] = "url-plugin";
    PluginType["Email"] = "email-plugin";
    PluginType["CurrencyConverter"] = "currency-converter-plugin";
    PluginType["Workflow"] = "workflow-plugin";
    PluginType["Commandline"] = "commandline-plugin";
    PluginType["SimpleFolderSearch"] = "simple-folder-search-plugin";
    PluginType["Uwp"] = "uwp";
    PluginType["ColorConverter"] = "color-converter";
    PluginType["Dictionary"] = "dictionary";
    PluginType["BrowserBookmarks"] = "browser-bookmarks";
    PluginType["Test"] = "test-plugin";
    PluginType["ControlPanel"] = "control-panel-plugin";
    PluginType["CsvReader"] = "csv-reader";
})(PluginType = exports.PluginType || (exports.PluginType = {}));
